"""
Program to create a custom iterator that returns numbers from 1 to N.
"""

class NumberIterator:
    """
    Iterator class that generates numbers from 1 to N
    """

    def __init__(self, last):
        self.last = last
        self.current = 1

    def __iter__(self):
        return self

    def __next__(self):
        # Stop iteration after reaching the last number
        if self.current > self.last:
            raise StopIteration

        number = self.current
        self.current += 1
        return number


def display_numbers():
    """
    Displays the numbers generated by the custom iterator
    """
    iterator = NumberIterator(22)

    for number in iterator:
        print(number)


if __name__ == "__main__":
    display_numbers()