"""
Program to generate square numbers up to N.
"""

def generate_squares(last):
    """
    Yield square numbers from 1 to the given last number
    """
    for number in range(1, last + 1):
        yield number ** 2


def display_squares():
    """
    Print square numbers generated by the generator
    """
    for square in generate_squares(10):
        print(square)


if __name__ == "__main__":
    display_squares()