spring.application.name=todo-app

# H2 Database Configuration

#creates in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
#default driver for H2
spring.datasource.driverClassName=org.h2.Driver
#default username/password
spring.datasource.username=sa
spring.datasource.password=

#automatically create tables from entity classes
spring.jpa.hibernate.ddl-auto=update
#show SQL queries in console 
spring.jpa.show-sql=true 

#enable browser UI for database
spring.h2.console.enabled=true 
#URL to open database UI
spring.h2.console.path=/h2-console 