package com.example.session2.component;

import com.example.session2.service.MessageFormatter;
import org.springframework.stereotype.Component;

@Component("longFormatter")
public class LongMessageFormatter implements MessageFormatter {

    @Override
    public String formatMessage() {
        return "This is a long message format generated by the system";
    }
}